<OEB> ::= <XMLVerion> <DOCTYPE> <Package>
<XMLVersion> ::= '<?xml version=' <AttributeVal> '?>'
<DOCTYPE>    ::= '<!DOCTYPE package PUBLIC' <AttributeVal> '>'

# package : order?
<Package>          ::= '<package' <PackageAttribute> '>' <MetaData> <ManifestTag> <SpineTag> <GuideTag> '</package>'
<PackageAttribute> ::= 'unique-identifier=' <AttributeVal>

# MetaData
<MetaData>        ::= '<metadata>' <DCMetaTag> '</metadata>'
<DCMetaTag>       ::= '<dc-metadata' <DCMetaAttribute> '>' <DC> '</dc-metadata>'
<DCMetaAttribute> ::= (xmls:dc|xmlns:oebpackage) '=' <AttributeVal> | <DCMetaAttribute> 
<DC>              ::= <DCIdTag> | <DCCreatorTag> | <DCContributorTag> | <DCTag> | <DCDateTag> | <DC> |

# DC Tags 
<DCIdTag>       ::= '<dc:Identifier' <DCIdAttribute> '>' <Text> '</dc:Identifier>'
<DCIdAttribute> ::= (id|scheme) '=' <AttributeVal> <DCIdAttribute> |  

<DCCreatorTag>       ::= '<dc:Creator' <DCCreatorAttribute> '>' <Text> '</dc:Creator>'
<DCContributorTag>   ::= '<dc:Contributor' <DCCreatorAttribute> '>' <Text> '</dc:Contributor>'
<DCCreatorAttribute> ::=  (role|file-as) '=' <AttributeVal> <DCCreatorAttribute> | 

<DCTag>   ::= '<dc:' <DCTitle>  '>' <Text> '</dc:' <DCTitle> '>'
<DCTitle> ::= Subject | Description | Publisher | Type | Format | Source | Coverage | Rights | Language | Relation

<DCDateTag>       ::= '<dc:Date' <DCDateAttribute> '>' <Text> '</dc:Date>'
<DCDateAttribute> ::= 'event=' <AttributeVal> |  

# Manifest
<ManifestTag>   ::= '<manifest>' <ItemTag> '</manifest>'
<ItemTag>       ::= '<item' <ItemAttribute> '/>' 
<ItemAttribute> ::= (id|href|media-type) '=' <AttributeVal> <ItemAttribute> |  

# Spine
<SpineTag>         ::= '<spine>' <ItemRefTag> '</spine>'
<ItemRefTag>       ::= '<itemref' <ItemRefAttribute> '/>' <ItemRefTag> | 
<ItemRefAttribute> ::=  'idref=' <AttributeVal>

# Guide
<GuideTag>           ::= '<guide>' <ReferenceTag> '</guide>'
<ReferenceTag>       ::= '<reference' <ReferenceAttribute> '/>' <ReferenceTag> | 
<ReferenceAttribute> ::= (type|title|href) '=' <AttributeVal> <ReferenceAttribute> |

<AttributeVal> ::= '"' <AttributeText> '"'
<AttributeText> ::= <Text> - '"'

<Text> ::= <Printable> | <Printable> <Text>
<Printable> ::= {Bet koks spausdinamas simbolis}
